-- Reconcile the 22 State Representative candidates missing from the updated
-- 2026 general-election candidate list. Street addresses from the source PDF
-- are intentionally not stored in public profile data.

INSERT INTO d1_people (
  filer_entity_number, firstname, middlename, lastname, display_name, slug,
  party, website_url, facebook_url, citizens_count_url, photo_url,
  is_2026_candidate, name_aliases, source, updated_at
)
VALUES
  ('sos-2026-house-belknap-5-eric-hoffman', 'Eric', NULL, 'Hoffman', 'Eric Hoffman',
   'sos-2026-house-belknap-5-eric-hoffman', 'Democratic Party',
   'https://erichoffman4nh.com/', NULL,
   'https://www.citizenscount.org/candidate/eric-hoffman',
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-belknap-5-eric-hoffman.jpg',
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-carroll-8-george-randell', 'George', NULL, 'Randell', 'George Randell',
   'sos-2026-house-carroll-8-george-randell', 'Independent',
   'http://www.georgerandell4nh.com/', NULL,
   'https://www.citizenscount.org/candidate/george-randell',
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-carroll-8-george-randell.png',
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-cheshire-6-sean-graves', 'Sean', NULL, 'Graves', 'Sean Graves',
   'sos-2026-house-cheshire-6-sean-graves', 'Republican Party',
   NULL, NULL, 'https://www.citizenscount.org/candidate/sean-graves', NULL,
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-coos-1-jay-ennis', 'Jay', NULL, 'Ennis', 'Jay Ennis',
   'sos-2026-house-coos-1-jay-ennis', 'Democratic Party',
   NULL, NULL, 'https://www.citizenscount.org/candidate/jay-ennis', NULL,
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-coos-4-dave-holmander', 'Dave', NULL, 'Holmander', 'Dave Holmander',
   'sos-2026-house-coos-4-dave-holmander', 'Democratic Party',
   NULL, NULL, NULL, NULL,
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-hillsborough-1-noah-lamoureaux', 'Noah', NULL, 'Lamoureaux', 'Noah Lamoureaux',
   'sos-2026-house-hillsborough-1-noah-lamoureaux', 'Democratic Party',
   NULL, NULL, 'https://www.citizenscount.org/candidate/noah-lamoureaux', NULL,
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-hillsborough-3-michael-joseph', 'Michael', NULL, 'Joseph', 'Michael Joseph',
   'sos-2026-house-hillsborough-3-michael-joseph', 'Democratic Party',
   NULL, NULL, 'https://www.citizenscount.org/candidate/michael-joseph', NULL,
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-hillsborough-13-don-staveley', 'Don', NULL, 'Staveley', 'Don Staveley',
   'sos-2026-house-hillsborough-13-don-staveley', 'Democratic Party',
   NULL, NULL, 'https://www.citizenscount.org/candidate/don-staveley', NULL,
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-hillsborough-16-maxine-mosley', 'Maxine', NULL, 'Mosley', 'Maxine Mosley',
   'sos-2026-house-hillsborough-16-maxine-mosley', 'Democratic Party',
   'https://www.mosley4nh.com/', 'https://www.facebook.com/Maxine4NH',
   'https://www.citizenscount.org/candidate/maxine-b-mosley',
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-hillsborough-16-maxine-mosley.jpg',
   1, 'Maxine B. Mosley', '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-hillsborough-24-jessica-margeson', 'Jessica', NULL, 'Margeson', 'Jessica Margeson',
   'sos-2026-house-hillsborough-24-jessica-margeson', 'Democratic Party',
   NULL, NULL, 'https://www.citizenscount.org/candidate/jessica-margeson', NULL,
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-hillsborough-38-heidi-p-jakoby', 'Heidi', 'P.', 'Jakoby', 'Heidi P. Jakoby',
   'sos-2026-house-hillsborough-38-heidi-p-jakoby', 'Democratic Party',
   'https://www.heidijakoby.com/', 'https://www.facebook.com/profile.php?id=100089992173073',
   'https://www.citizenscount.org/candidate/heidi-jakoby',
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-hillsborough-38-heidi-p-jakoby.png',
   1, 'Heidi Jakoby', '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-hillsborough-39-jon-dipietro', 'Jon', NULL, 'DiPietro', 'Jon DiPietro',
   'sos-2026-house-hillsborough-39-jon-dipietro', 'Republican Party',
   'https://www.jondipietro.com/', NULL,
   'https://www.citizenscount.org/candidate/jon-dipietro',
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-hillsborough-39-jon-dipietro.jpg',
   1, 'Jon Dipietro', '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-merrimack-9-john-f-martin', 'John', 'F.', 'Martin', 'John F. Martin',
   'sos-2026-house-merrimack-9-john-f-martin', 'Republican Party',
   NULL, 'https://www.facebook.com/MartinNhHouse/', NULL,
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-merrimack-9-john-f-martin.jpg',
   1, 'John Martin', '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-merrimack-9-matthew-poulin', 'Matthew', NULL, 'Poulin', 'Matthew Poulin',
   'sos-2026-house-merrimack-9-matthew-poulin', 'Republican Party',
   NULL, 'https://www.facebook.com/profile.php?id=61563525145046',
   'https://www.citizenscount.org/candidate/matthew-poulin',
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-merrimack-9-matthew-poulin.jpg',
   1, 'Matt Poulin', '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-rockingham-2-kendra-cohen', 'Kendra', NULL, 'Cohen', 'Kendra Cohen',
   'sos-2026-house-rockingham-2-kendra-cohen', 'Democratic Party',
   NULL, 'https://www.facebook.com/KendraforNH/',
   'https://www.citizenscount.org/candidate/kendra-cohen',
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-rockingham-2-kendra-cohen.jpg',
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-rockingham-2-robert-prieto', 'Robert', NULL, 'Prieto', 'Robert Prieto',
   'sos-2026-house-rockingham-2-robert-prieto', 'Democratic Party',
   NULL, 'https://www.facebook.com/RobertForNHStateRep',
   'https://www.citizenscount.org/candidate/robert-prieto',
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-rockingham-2-robert-prieto.jpg',
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-rockingham-16-neil-marceau', 'Neil', NULL, 'Marceau', 'Neil Marceau',
   'sos-2026-house-rockingham-16-neil-marceau', 'Democratic Party',
   NULL, NULL, 'https://www.citizenscount.org/candidate/neil-marceau', NULL,
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-rockingham-18-beth-cacciotti', 'Beth', NULL, 'Cacciotti', 'Beth Cacciotti',
   'sos-2026-house-rockingham-18-beth-cacciotti', 'Democratic Party',
   NULL, 'https://www.facebook.com/CacciottiStateRep/',
   'https://www.citizenscount.org/candidate/beth-m-cacciotti',
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-rockingham-18-beth-cacciotti.jpg',
   1, 'Beth M. Cacciotti', '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-strafford-5-william-f-fessenden', 'William', 'F.', 'Fessenden', 'William F. Fessenden',
   'sos-2026-house-strafford-5-william-f-fessenden', 'Independent',
   'https://fessendenfornh.net/', NULL,
   'https://www.citizenscount.org/candidate/william-f-fessenden', NULL,
   1, 'William Fessenden', '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP),
  ('sos-2026-house-strafford-12-omero-ambriz', 'Omero', NULL, 'Ambriz', 'Omero Ambriz',
   'sos-2026-house-strafford-12-omero-ambriz', 'Republican Party',
   'https://www.greaterdovergop.org/omero-ambriz', NULL, NULL,
   'https://photos.nhdeservesbetter.com/candidates/sos-2026-house-strafford-12-omero-ambriz.webp',
   1, NULL, '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP)
ON CONFLICT(filer_entity_number) DO UPDATE SET
  firstname = excluded.firstname,
  middlename = excluded.middlename,
  lastname = excluded.lastname,
  display_name = excluded.display_name,
  party = excluded.party,
  website_url = COALESCE(NULLIF(excluded.website_url, ''), d1_people.website_url),
  facebook_url = COALESCE(NULLIF(excluded.facebook_url, ''), d1_people.facebook_url),
  citizens_count_url = COALESCE(NULLIF(excluded.citizens_count_url, ''), d1_people.citizens_count_url),
  photo_url = COALESCE(NULLIF(excluded.photo_url, ''), d1_people.photo_url),
  is_2026_candidate = 1,
  name_aliases = COALESCE(NULLIF(excluded.name_aliases, ''), d1_people.name_aliases),
  source = excluded.source,
  updated_at = CURRENT_TIMESTAMP;

-- Brian Cole and Corinne Cascadden already have canonical person profiles.
UPDATE d1_people
SET is_2026_candidate = 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN (96, 447);

WITH roles(person_filer, role_filer, county, district, political_party) AS (
  VALUES
    ('sos-2026-house-belknap-5-eric-hoffman', 'sos-2026-house-belknap-5-eric-hoffman', 'Belknap', '5', 'Democratic Party'),
    ('sos-2026-house-carroll-8-george-randell', 'sos-2026-house-carroll-8-george-randell', 'Carroll', '8', 'Independent'),
    ('sos-2026-house-cheshire-6-sean-graves', 'sos-2026-house-cheshire-6-sean-graves', 'Cheshire', '6', 'Republican Party'),
    ('sos-2026-house-coos-1-jay-ennis', 'sos-2026-house-coos-1-jay-ennis', 'Coos', '1', 'Democratic Party'),
    ('sos-2026-house-coos-4-dave-holmander', 'sos-2026-house-coos-4-dave-holmander', 'Coos', '4', 'Democratic Party'),
    ('242608', '242608', 'Coos', '7', 'Democratic Party'),
    ('sos-2026-house-hillsborough-1-noah-lamoureaux', 'sos-2026-house-hillsborough-1-noah-lamoureaux', 'Hillsborough', '1', 'Democratic Party'),
    ('sos-2026-house-hillsborough-3-michael-joseph', 'sos-2026-house-hillsborough-3-michael-joseph', 'Hillsborough', '3', 'Democratic Party'),
    ('sos-2026-house-hillsborough-13-don-staveley', 'sos-2026-house-hillsborough-13-don-staveley', 'Hillsborough', '13', 'Democratic Party'),
    ('sos-2026-house-hillsborough-16-maxine-mosley', 'sos-2026-house-hillsborough-16-maxine-mosley', 'Hillsborough', '16', 'Democratic Party'),
    ('sos-2026-house-hillsborough-24-jessica-margeson', 'sos-2026-house-hillsborough-24-jessica-margeson', 'Hillsborough', '24', 'Democratic Party'),
    ('242617', '242617', 'Hillsborough', '26', 'Republican Party'),
    ('sos-2026-house-hillsborough-38-heidi-p-jakoby', 'sos-2026-house-hillsborough-38-heidi-p-jakoby', 'Hillsborough', '38', 'Democratic Party'),
    ('sos-2026-house-hillsborough-39-jon-dipietro', 'sos-2026-house-hillsborough-39-jon-dipietro', 'Hillsborough', '39', 'Republican Party'),
    ('sos-2026-house-merrimack-9-john-f-martin', 'sos-2026-house-merrimack-9-john-f-martin', 'Merrimack', '9', 'Republican Party'),
    ('sos-2026-house-merrimack-9-matthew-poulin', 'sos-2026-house-merrimack-9-matthew-poulin', 'Merrimack', '9', 'Republican Party'),
    ('sos-2026-house-rockingham-2-kendra-cohen', 'sos-2026-house-rockingham-2-kendra-cohen', 'Rockingham', '2', 'Democratic Party'),
    ('sos-2026-house-rockingham-2-robert-prieto', 'sos-2026-house-rockingham-2-robert-prieto', 'Rockingham', '2', 'Democratic Party'),
    ('sos-2026-house-rockingham-16-neil-marceau', 'sos-2026-house-rockingham-16-neil-marceau', 'Rockingham', '16', 'Democratic Party'),
    ('sos-2026-house-rockingham-18-beth-cacciotti', 'sos-2026-house-rockingham-18-beth-cacciotti', 'Rockingham', '18', 'Democratic Party'),
    ('sos-2026-house-strafford-5-william-f-fessenden', 'sos-2026-house-strafford-5-william-f-fessenden', 'Strafford', '5', 'Independent'),
    ('sos-2026-house-strafford-12-omero-ambriz', 'sos-2026-house-strafford-12-omero-ambriz', 'Strafford', '12', 'Republican Party')
)
INSERT INTO d1_person_candidate_roles (
  person_id, filer_entity_number, office_type, office, county, district,
  political_party, election_year, election_cycle, total_raised, total_spent,
  status, source, updated_at
)
SELECT
  p.id, roles.role_filer, 'General Court', 'State Representative',
  roles.county, roles.district, roles.political_party, 2026,
  '2026 Election Cycle', 0, 0, 'active',
  '2026-general-candidate-list-2026-10-04', CURRENT_TIMESTAMP
FROM roles
JOIN d1_people p ON p.filer_entity_number = roles.person_filer
ON CONFLICT(filer_entity_number, election_year) DO UPDATE SET
  person_id = excluded.person_id,
  office_type = excluded.office_type,
  office = excluded.office,
  county = excluded.county,
  district = excluded.district,
  political_party = excluded.political_party,
  election_cycle = excluded.election_cycle,
  status = 'active',
  source = excluded.source,
  updated_at = CURRENT_TIMESTAMP;
